### PR TITLE
#66 - Async Repository, IOException usage reduced

### PR DESCRIPTION
**Pull request by olegmoz**
Part of #66 
Async `Repository`, `IOException` usage reduced

### CODE REVIEW

**Review by olenagerasimova — APPROVED** [review]
@olegmoz looks good to merge, though you need to fix the build

**Comment by olegmoz** [comment]
@olenagerasimova I had to disable IT tests, they are failing due to update of composer adapter utility. Puzzle was added to resolve this problem later. Please review

**Review by olenagerasimova — APPROVED** [review]
@olegmoz approving

**Comment by 0crat** [comment]
Job `gh:artipie/composer-adapter#68` is not assigned, can't get performer

**Pull request merged**
