### PR TITLE
#35 - Migrated to HTTP 0.5

### PR DESCRIPTION
**Pull request by olegmoz**
Closes issue #35
Migration to HTTP 0.5

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#36](https://github.com/artipie/composer-adapter/issues/36) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/907c2f08-8a01-4e41-bd7b-df636baa5046); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@olegmoz please check merge conflicts

**Comment by olegmoz** [comment]
@g4s8 merged with master and resolved conflicts, please review.

**Comment by g4s8** [comment]
@olegmoz it seems you've mistyped the ticket number to close, I'll change it to #35

**Comment by 0crat** [comment]
Job was finished in 22 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)[/z](https://www.0crat.com/u/carlosmiranda) didn't make CR comments

**Pull request merged**
