### PR TITLE
#1 - Added pom.xml

### PR DESCRIPTION
**Pull request by olegmoz**

### CODE REVIEW

**Comment by olegmoz** [comment]
@0crat status

**Comment by 0crat** [comment]
I'm not managing `artipie/composer-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by olegmoz** [comment]
@0crat status

**Comment by g4s8** [comment]
@0crat elect

**Comment by yegor256** [comment]
@olegmoz let's use parent POM as it's done in `rpm-adapter` and `npm-adapter`

**Comment by yegor256** [comment]
@olegmoz thanks!

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/composer-adapter/issues/3#issuecomment-582274264))

@olegmoz This is what I know about this job in [CT2E6TK9B](https://www.0crat.com/p/CT2E6TK9B), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#3](https://github.com/artipie/composer-adapter/issues/3) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fcomposer-adapter%233%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Job `gh:artipie/composer-adapter#3` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
