### PR TITLE
#2 - Added brief project description and useful links to README.md

### PR DESCRIPTION
**Pull request by olegmoz**

### CODE REVIEW

**Comment by olegmoz** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/composer-adapter/issues/4#issuecomment-582306154))

@olegmoz This is what I know about this job in [CT2E6TK9B](https://www.0crat.com/p/CT2E6TK9B), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#4](https://github.com/artipie/composer-adapter/issues/4) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fcomposer-adapter%234%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by yegor256** [comment]
@olegmoz thanks!

**Comment by 0crat** [comment]
Job `gh:artipie/composer-adapter#4` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
